server.port=${PORT:8080}
spring.config.import=optional:file:./config.properties

db.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:freelancehub}?useSSL=true&serverTimezone=UTC
db.user=${DB_USER:root}
db.password=${DB_PASSWORD:}
gemini.api.key=${GEMINI_API_KEY:}
